apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-writer
  template:
    metadata:
      labels:
        app: mysql-writer
    spec:
      containers:
      - name: writer
        image: udit7803/mysql-writer:v1
        ports:
        - containerPort: 8000
