apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk  # base64 encoded "rootpassword"
  replication-password: cmVwbGljYXRpb25wYXNzd29yZA==  # base64 encoded "replicationpassword"
