apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-slave
  template:
    metadata:
      labels:
        app: mysql-slave
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root-password
        - name: MYSQL_DATABASE
          value: "testdb"
        - name: MYSQL_MASTER_HOST
          value: "mysql-master"
        - name: MYSQL_MASTER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: replication-password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
spec:
  ports:
  - port: 3306
  selector:
    app: mysql-slave
